/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zerotierone_sdk_PacketSender */

#ifndef _Included_com_zerotierone_sdk_PacketSender
#define _Included_com_zerotierone_sdk_PacketSender
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
