/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zerotierone_sdk_VirtualNetworkConfig */

#ifndef _Included_com_zerotierone_sdk_VirtualNetworkConfig
#define _Included_com_zerotierone_sdk_VirtualNetworkConfig
#ifdef __cplusplus
extern "C" {
#endif
#undef com_zerotierone_sdk_VirtualNetworkConfig_MAX_MULTICAST_SUBSCRIPTIONS
#define com_zerotierone_sdk_VirtualNetworkConfig_MAX_MULTICAST_SUBSCRIPTIONS 4096L
#ifdef __cplusplus
}
#endif
#endif
