/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zerotierone_sdk_Node */

#ifndef _Included_com_zerotierone_sdk_Node
#define _Included_com_zerotierone_sdk_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    node_init
 * Signature: (J)Lcom/zerotierone/sdk/ResultCode;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_node_1init
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    node_delete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zerotierone_sdk_Node_node_1delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    processVirtualNetworkFrame
 * Signature: (JJJJJII[B[J)Lcom/zerotierone/sdk/ResultCode;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_processVirtualNetworkFrame
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jint, jint, jbyteArray, jlongArray);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    processWirePacket
 * Signature: (JJLjava/net/InetSockAddress;I[B[J)Lcom/zerotierone/sdk/ResultCode;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_processWirePacket
  (JNIEnv *, jobject, jlong, jlong, jobject, jint, jbyteArray, jlongArray);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    processBackgroundTasks
 * Signature: (JJ[J)Lcom/zerotierone/sdk/ResultCode;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_processBackgroundTasks
  (JNIEnv *, jobject, jlong, jlong, jlongArray);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    join
 * Signature: (JJ)Lcom/zerotierone/sdk/ResultCode;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_join
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    leave
 * Signature: (JJ)Lcom/zerotierone/sdk/ResultCode;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_leave
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    multicastSubscribe
 * Signature: (JJJJ)Lcom/zerotierone/sdk/ResultCode;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_multicastSubscribe
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    multicastUnsubscribe
 * Signature: (JJJJ)Lcom/zerotierone/sdk/ResultCode;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_multicastUnsubscribe
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    address
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_zerotierone_sdk_Node_address
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    status
 * Signature: (J)Lcom/zerotierone/sdk/NodeStatus;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_status
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    networkConfig
 * Signature: (JJ)Lcom/zerotierone/sdk/VirtualNetworkConfig;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_networkConfig
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    version
 * Signature: ()Lcom/zerotierone/sdk/Version;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_version
  (JNIEnv *, jobject);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    peers
 * Signature: (J)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_peers
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zerotierone_sdk_Node
 * Method:    networks
 * Signature: (J)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_zerotierone_sdk_Node_networks
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
