# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//:__subpackages__"])

config_setting(
    name = "windows",
    constraint_values = ["@platforms//os:windows"],
)
