# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

ARG BASE_IMAGE=alpine:latest
ARG CORES=${nproc}

FROM ${BASE_IMAGE} as final

RUN apk update

RUN apk add --update alpine-sdk \
    && apk add cmake openssl openssl-dev g++ \
    curl-dev git autoconf libtool linux-headers \
    libevent-dev openssl-dev

RUN mkdir -p /opt/third_party/install

WORKDIR /opt
