---
clone:
  depth: 1
kind: pipeline
name: el6 amd64 build
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/build.sh el6 redhat amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: build
  when:
    event:
    - push
- commands:
  - ./ci/scripts/build.sh el6 redhat amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: release
  when:
    event:
    - tag
- commands:
  - ./ci/scripts/publish.sh el6 redhat amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/publish.sh el6 redhat amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: copy relase
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- el6 amd64 build
kind: pipeline
name: el6 index
platform:
  os: linux
pull: always
steps:
- commands:
  - /usr/local/bin/index zerotier-builds redhat el6 amd64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/dnf-builder
  name: index build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - /usr/local/bin/index zerotier-releases redhat el6 amd64
  environment:
    GPG_PRIVATE_KEY:
      from_secret: gpg-private-key
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/dnf-builder
  name: index release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
clone:
  depth: 1
depends_on:
- el6 index
kind: pipeline
name: el6 amd64 test
platform:
  os: linux
pull: always
steps:
- commands:
  - ./ci/scripts/test.sh el6 redhat amd64 100.0.0+${DRONE_COMMIT_SHA:0:8} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test build
  volumes:
  - name: zerotier-builds
    path: /zerotier-builds
  when:
    event:
    - push
- commands:
  - ./ci/scripts/test.sh el6 redhat amd64 ${DRONE_TAG} ${DRONE_BUILD_EVENT}
  image: 084037375216.dkr.ecr.us-east-2.amazonaws.com/honda-builder
  name: test release
  volumes:
  - name: zerotier-releases
    path: /zerotier-releases
  when:
    event:
    - tag
trigger:
  event:
  - push
  - tag
  - custom
type: docker
volumes:
- host:
    path: /zerotier-builds
  name: zerotier-builds
- host:
    path: /zerotier-releases
  name: zerotier-releases
---
kind: signature
hmac: 0c18860540ec23fe2a3d081f5b76e75f61b9a8258cc82eda98950242e84ab1ec

...
