FROM debian:bookworm



RUN apt update && apt upgrade -y
RUN apt -y install \
    netcat-traditional \
    postgresql-client \
    postgresql-client-common \
    libjemalloc2 \
    libpq5 \
    curl \
    binutils \
    perf-tools-unstable \
    google-perftools \
    gnupg \
    libgrpc++1.51 \
    libgrpc29 

