FROM ubuntu:jammy

RUN apt update && apt upgrade -y

RUN apt -y install \
    postgresql-client \
    postgresql-client-common \
    libjemalloc2 \
    libpq5 \
    curl \
    binutils \
    linux-tools-gke \
    perf-tools-unstable \
    google-perftools
