#define PRODUCT_NAME			"ZeroTier One Ethernet Tap"
#define PRODUCT_VERSION			"1.0.0"
#define PRODUCT_VERSION_RESOURCE	1,0,0,1
#define PRODUCT_TAP_WIN_COMPONENT_ID	"ztTap100"
#define PRODUCT_TAP_WIN_MAJOR		1
#define PRODUCT_TAP_WIN_MINOR		0
#define PRODUCT_TAP_WIN_PROVIDER		"ZeroTier Networks"
#define PRODUCT_TAP_WIN_DEVICE_DESCRIPTION	PRODUCT_NAME
#define PRODUCT_TAP_WIN_RELDATE		"01/20/2014"

#define TAP_DRIVER_MAJOR_VERSION PRODUCT_TAP_WIN_MAJOR
#define TAP_DRIVER_MINOR_VERSION PRODUCT_TAP_WIN_MINOR
