#define PRODUCT_NAME			"ZeroTier One Virtual Network Port"
#define PRODUCT_VERSION			"2.0.0"
#define PRODUCT_VERSION_RESOURCE	2,0,0,1
#define PRODUCT_TAP_WIN_COMPONENT_ID	"zttap200"
#define PRODUCT_TAP_WIN_MAJOR		2
#define PRODUCT_TAP_WIN_MINOR		0
#define PRODUCT_TAP_WIN_PROVIDER		"ZeroTier Networks"
#define PRODUCT_TAP_WIN_DEVICE_DESCRIPTION	PRODUCT_NAME
#define PRODUCT_TAP_WIN_RELDATE		"01/22/2014"

#define TAP_DRIVER_MAJOR_VERSION PRODUCT_TAP_WIN_MAJOR
#define TAP_DRIVER_MINOR_VERSION PRODUCT_TAP_WIN_MINOR
