#!/bin/sh -e

case "$1" in
  configure)
      if ! id zerotier-one >>/dev/null 2>&1; then
        adduser --system --group --home /var/lib/zerotier-one --no-create-home zerotier-one
      fi
      ;;
esac

#DEBHELPER#
