/*
#define PRODUCT_NAME			"@PRODUCT_NAME@"
#define PRODUCT_VERSION			"@PRODUCT_VERSION@"
#define PRODUCT_VERSION_RESOURCE	@PRODUCT_VERSION_RESOURCE@
#define PRODUCT_TAP_WIN_COMPONENT_ID	"@PRODUCT_TAP_WIN_COMPONENT_ID@"
#define PRODUCT_TAP_WIN_MAJOR		@PRODUCT_TAP_WIN_MAJOR@
#define PRODUCT_TAP_WIN_MINOR		@PRODUCT_TAP_WIN_MINOR@
#define PRODUCT_TAP_WIN_PROVIDER		"@PRODUCT_TAP_WIN_PROVIDER@"
#define PRODUCT_TAP_WIN_DEVICE_DESCRIPTION	"@PRODUCT_TAP_WIN_DEVICE_DESCRIPTION@"
#define PRODUCT_TAP_WIN_RELDATE		"@PRODUCT_TAP_WIN_RELDATE@"
*/
#define PRODUCT_NAME			"ZeroTier One Virtual Network Port"
#define PRODUCT_VERSION			"3.0.0"
#define PRODUCT_VERSION_RESOURCE	3,0,0,1
#define PRODUCT_TAP_WIN_COMPONENT_ID	"zttap300"
#define PRODUCT_TAP_WIN_MAJOR		3
#define PRODUCT_TAP_WIN_MINOR		0
#define PRODUCT_TAP_WIN_PROVIDER		"ZeroTier Networks"
#define PRODUCT_TAP_WIN_DEVICE_DESCRIPTION	PRODUCT_NAME
#define PRODUCT_TAP_WIN_RELDATE		"04/24/2015"
